name: Delete Old Packages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/delete-package-versions@v5
      with:
        package-name: 'cuda-actions-runner'
        package-type: 'container'
        min-versions-to-keep: 5
        token: ${{ secrets.API_TOKEN_GITHUB_PACKAGES }}
